[workspace]

members = [
    "qvopenapi",
    "qvopenapi-sys",
    "qvopenapi-http",
]


# https://github.com/rust-lang/rust/issues/79609
# To bypass missing 'dwarf' exception handling on mingw i686 installations,
# set panic = abort and provide mock unwind symbol to the linker
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
