[workspace]

members = [
    "qvopenapi",
    "qvopenapi-sys",
    "qvopenapi-http",
]

[workspace.dependencies]
libc = "0.2"
libloading = "0.8"
windows-sys = {version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]}
custom_error = "1.9.2"
