[package]
name = "qvopenapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qvopenapi-sys = { path = "../qvopenapi-sys" }
custom_error = { workspace = true }
libloading = { workspace = true }

[features]
disable-unwind = [ "qvopenapi-sys/disable-unwind" ]
